name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build & Test
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-restore --no-build --configuration Release